# Generated by Django 3.0.4 on 2020-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(default='', max_length=50)),
                ('app_type', models.CharField(choices=[('public', 'Public'), ('custom', 'Custom')], default='public', max_length=50)),
                ('access_token', models.CharField(default='', max_length=200)),
                ('custom_app_api_key', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('custom_app_api_secret_key', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
