# Generated by Django 3.0.4 on 2020-03-22 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_framework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=50)),
                ('graph_id', models.CharField(default='', max_length=70)),
                ('rest_id', models.BigIntegerField(default=0)),
                ('auth_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_framework.AuthShop')),
            ],
        ),
    ]
