# Generated by Django 3.0.4 on 2020-03-22 03:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_framework', '0002_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='graph_id',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='rest_id',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='topic',
            field=models.CharField(choices=[('carts/create', 'carts/create'), ('carts/update', 'carts/update'), ('checkouts/create', 'checkouts/create'), ('checkouts/update', 'checkouts/update'), ('checkouts/delete', 'checkouts/delete'), ('collections/create', 'collections/create'), ('collections/update', 'collections/update'), ('collections/delete', 'collections/delete'), ('collection_listings/add', 'collection_listings/add'), ('collection_listings/update', 'collection_listings/update'), ('collection_listings/remove', 'collection_listings/remove'), ('customers/create', 'customers/create'), ('customers/disable', 'customers/disable'), ('customers/enable', 'customers/enable'), ('customers/update', 'customers/update'), ('customers/delete', 'customers/delete'), ('customer_groups/create', 'customer_groups/create'), ('customer_groups/update', 'customer_groups/update'), ('customer_groups/delete', 'customer_groups/delete'), ('draft_orders/create', 'draft_orders/create'), ('draft_orders/update', 'draft_orders/update'), ('draft_orders/delete', 'draft_orders/delete'), ('fulfillments/create', 'fulfillments/create'), ('fulfillments/update', 'fulfillments/update'), ('fulfillment_events/create', 'fulfillment_events/create'), ('fulfillment_events/delete', 'fulfillment_events/delete'), ('inventory_items/create', 'inventory_items/create'), ('inventory_items/update', 'inventory_items/update'), ('inventory_items/delete', 'inventory_items/delete'), ('inventory_levels/connect', 'inventory_levels/connect'), ('inventory_levels/disconnect', 'inventory_levels/disconnect'), ('inventory_levels/update', 'inventory_levels/update'), ('locations/create', 'locations/create'), ('locations/update', 'locations/update'), ('locations/delete', 'locations/delete'), ('orders/cancelled', 'orders/cancelled'), ('orders/create', 'orders/create'), ('orders/fulfilled', 'orders/fulfilled'), ('orders/paid', 'orders/paid'), ('orders/partially_fulfilled', 'orders/partially_fulfilled'), ('orders/updated', 'orders/updated'), ('orders/delete', 'orders/delete'), ('orders/edited', 'orders/edited'), ('order_transactions/create', 'order_transactions/create'), ('products/create', 'products/create'), ('products/update', 'products/update'), ('products/delete', 'products/delete'), ('product_listings/add', 'product_listings/add'), ('product_listings/update', 'product_listings/update'), ('product_listings/remove', 'product_listings/remove'), ('refunds/create', 'refunds/create'), ('app/uninstalled', 'app/uninstalled'), ('shop/update', 'shop/update'), ('locales/create', 'locales/create'), ('locales/update', 'locales/update'), ('tender_transactions/create', 'tender_transactions/create'), ('themes/create', 'themes/create'), ('themes/publish', 'themes/publish'), ('themes/update', 'themes/update'), ('themes/delete', 'themes/delete')], default='', max_length=50),
        ),
    ]
