# Generated by Django 3.0.4 on 2020-03-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_framework', '0003_auto_20200322_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='graph_id',
        ),
    ]
